version: "3.9"

services:
  app:
    image: wolverine
    container_name: WOLverine
    ports:
      - "5000:5000"
    volumes:
      - /opt/docker/volumes/WOLverine/instance:/WOLverine/instance
      - /opt/docker/volumes/WOLverine/jobs.db:/WOLverine/jobs.db
    restart: unless-stopped
